### ISSUE TITLE
Common class for Exceptions

### ISSUE THREAD

**Issue by adaedra** [contactually/zuora-ruby#57]
Hello,

Currently, zuora-ruby exceptions classes are all direct children of StandardError. It would be handy to have a common parent class we could rescue from to catch all errors from this gem easily.

**Comment by jwg2s** [comment]
@adaedra many errors raised by Zuora's API are raised as `Zuora::Errors::InvalidValue` exceptions.  Whatever error message Zuora's API returns is used as the error class's message.

That error class does inherit from `StandardError` however.  What were you thinking as an alternative?

**Comment by adaedra** [comment]
I opened a PR with what I had in mind.

The problem is that with current hierarchy, I can't catch easily (other than putting in line all exceptions) zuora-related errors, whatever they are Non-200 returns, connections errors or whatever.

Rescuing `StandardError` would not be good as I would catch other errors I don't want to take care of here – including other exceptions I may be rising in a current block. I need an additional level of granularity between `StandardError` and leaf exception classes.

**Comment by adaedra** [comment]
Since the associated PR is merged, I closed the issue.

Thanks!
