### ISSUE TITLE
SSL verification at false?

### ISSUE THREAD

**Issue by rclavel** [contactually/zuora-ruby#59]
Hello,

Why do you disable the SSL verification in the REST Client?

It is dangerous:
`Faraday.new(url, ssl: { verify: false })` in https://github.com/contactually/zuora-ruby/blob/develop/lib/zuora/rest/client.rb#L117

Thanks,

**Comment by jwg2s** [comment]
@rclavel good catch - we disabled it during active development because Zuora was running into SSL errors with their sandbox environment.  I'll open a PR to fix this issue.

**Comment by rclavel** [comment]
Thanks @jwg2s  👍

**Comment by jwg2s** [comment]
@rclavel thanks for bringing it to our attention!  I think we're closing to cutting a v1.0.

**Comment by adaedra** [comment]
@jwg2s: Would it be at least possible to release a (minor) version with this change? Thanks

**Comment by jwg2s** [comment]
@adaedra sorry for the delay!  I'll try to get a new version pushed up today or tomorrow.
