### ISSUE TITLE
Subscribe Call Issues

### ISSUE THREAD

**Issue by Henry-L** [contactually/zuora-ruby#61]
Currently, the way you have set up the `subscribe` call does not allow you to subscribe with an account that already exists and also does not give you the option to pass in a `RatePlanCharge`.

When making a `subscribe` call with an active account that already exists, `bill_to_contact` is no longer required since that is already on the account object.

Also, within `RatePlanData`, there should an optional parameter `RatePlanChargeData` which holds at least one `RatePlanCharge`. This allows you to put a specific quantity on the subscription and have it be active on completion of the subscribe call.

**Comment by engpeter2010** [comment]
If you can fix this, it will be good option in this library because zuora subscriptions are essential component.

**Comment by jwg2s** [comment]
@Henry-L I noticed you guys have forked the repo and made some improvements.  Mind submitting a pull request and I can publish an update to the gem?

Thanks!
