### ISSUE TITLE
REST: Better Exception Messages

### ISSUE THREAD

**Issue by sshaw** [contactually/zuora-ruby#62]
Currently an `ErrorResponse` for a non 200 has a message of: `Non-200`. Not too helpful. 
To find out why, one has to dig in to the Faraday response included in the exception.   This should be done by the rest client. The message should be whatever is in `response.body["reasons"]`. 

In general exposing an implementation detail like `Faraday::Response` is not a good idea.

**Comment by coxw** [comment]
@sshaw https://github.com/contactually/zuora-ruby/pull/66  How is that?

**Comment by coxw** [comment]
This has been merged into develop

**Comment by sshaw** [comment]
> @sshaw #66 How is that?

Great! 👍
