### ISSUE TITLE
REST: Setting Header With API Version

### ISSUE THREAD

**Issue by sshaw** [contactually/zuora-ruby#63]
Is there a reason this is not supported?

**Comment by coxw** [comment]
@jwg2s  @sshaw https://github.com/contactually/zuora-ruby/pull/67  I have added the ability to set this in your environment.  I don't think it needs to be set per call based on how often it appears minor versions are used.  Simple, you set a version (196.0 for invoice/collect params on subscriptions) and it will use it.  https://knowledgecenter.zuora.com/DC_Developers/C_REST_API/A_REST_basics#Zuora_REST_API_Versions

**Comment by coxw** [comment]
This has been merged into develop

**Comment by jwg2s** [comment]
Fixed by #67
