### ISSUE TITLE
REST response in JSON format?

### ISSUE THREAD

**Issue by yihaoye** [contactually/zuora-ruby#65]
Hi, the REST response is Faraday::Response object, any way to convert it into JSON? Thanks!

**Comment by jwg2s** [comment]
@yihaoye you can call `JSON.parse(response.body)`, our ability to invest in this gem at the moment isn't that high, but we'd definitely be willing to accept PRs!

**Comment by yihaoye** [comment]
@jwg2s Thanks man, your answer solve my problem.
