### ISSUE TITLE
Zuora has migrated to a new endpoint

### ISSUE THREAD

**Issue by coxw** [contactually/zuora-ruby#69]
https://www.zuora.com/developer/api-reference/#section/Introduction/Endpoints

Zuora has migrated to a new API endpoint, which appears to be a new infrastructure in the move away from the REST API using the SOAP API in the background.  It is now rest.zuora.com/v1.  Just updating this throughout the code will most likely break all active uses of this gem, so something will need to be done that is backwards compatible since you no longer need /rest/v1, just /v1 in the path.

The new endpoint is more scalable and supports the new action endpoints not available in the old endpoint: https://www.zuora.com/developer/api-reference/#tag/Actions

**Comment by jwg2s** [comment]
@coxw we could have the gem be initialized with an API version (which defaults to the currently implemented version) and can be overridden by the gem user.

**Comment by coxw** [comment]
@jwg2s Good idea - Are you thinking something more like @client ||= Zuora::Rest::ClientV2.new(ENV["ZUORA_USERNAME"], ENV["ZUORA_PASSWORD"], use_sandbox?) where ClientV2 inherits from Client?   What's annoying is that for the new calls they added the structure is different on the request and response.  https://www.zuora.com/developer/api-reference/#tag/Actions - Notice how it is 'Success' and not 'success' and 'Errors' instead of 'reasons'?  It is only for those /actions/ calls.  The rest of the API endpoints response as they previously did.

**Comment by coxw** [comment]
@jwg2s Not the best solution, but this adds backwards compatible support as well as another client for bulk api actions: https://github.com/contactually/zuora-ruby/pull/70/files

**Comment by coxw** [comment]
@jwg2s Any feedback? We are using this in production fine on a different fork

**Comment by jwg2s** [comment]
@coxw haven't had time to review recently but will try to get to it this week or early next week.  I've been meaning to come back and do a bunch of investment in this repo

**Comment by coxw** [comment]
@jwg2s Sounds good - no rush.  If you document some of the enhancements desired, I can either help out or provide feedback based on what we have seen.

**Comment by thelostspore** [comment]
We're in the same boat as @coxw. Perhaps the pull can be split into two to expedite the merge (update base api endpoints and `rest/bulk_client` additions?). I've also made a [comment](https://github.com/contactually/zuora-ruby/pull/70/files#r131992882) on the pull with some info from Zuora's latest API release notes.

**Comment by coxw** [comment]
@jwg2s Added comments to the PR.  @thelostspore has good points, but more so for a major release.  The intention of this PR was to get us up to full functionality that is offered at https://www.zuora.com/developer/api-reference/ while being non-intrusive to existing applications.  Having migrated to this PR from the existing production version, I can say this has worked well, especially for the bulk operations that most companies with a complex integration into Zuora will need.

**Comment by coxw** [comment]
This has been merged
